name: Send discord notification
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: step-security/action-discord@a67f622d551a2f5fcc316c78e0076fe665ff6637 # v0.1.0
        with:
          args:  "${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }} status https://hips.hedera.com/hip/${{ github.event.inputs.filename }}"