name: Send discord notification
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: step-security/action-discord@5e8cd69d2f322a15430c4d13a97659b58031d207 # v0.1.1
        with:
          args:  "${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }} status https://hips.hedera.com/hip/${{ github.event.inputs.filename }}"